spring.application.name=spring-jwt-template

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jwt.secret_key=${SPRING_JWT_SECRET_KEY}
spring.cors.allowed-origins=${SPRING_CORS_ALLOWED_ORIGINS}